// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $resume from "./routes/resume.tsx";
import * as $LowPolyAvatar from "./islands/LowPolyAvatar.tsx";
import * as $PageMenu from "./islands/PageMenu.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/resume.tsx": $resume,
  },
  islands: {
    "./islands/LowPolyAvatar.tsx": $LowPolyAvatar,
    "./islands/PageMenu.tsx": $PageMenu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
